### ISSUE TITLE
Compile problem of AURORA

### ISSUE THREAD

**Issue by zxkjack123** [asipp-neutronics/aurora#2]

**Comment by shizhiqijlu** [comment]
## problem
compile error while running ./scripts/build-aurora.sh
## platform
wsl ubuntu
aurora does not specify exact version of moose needed neither in readme nor in build_moose.sh
## error information
In file included from /home/username/projects/aurora/aurora/openmc/src/problem/OpenMCProblem.C:1,
                 from /home/username/projects/aurora/aurora/openmc/build/unity_src/problem_Unity.C:2:
/home/username/projects/aurora/aurora/openmc/build/header_symlinks/OpenMCProblem.h:26:16: error: 'virtual bool OpenMCProblem::converged()' marked 'override', but does not override
   26 |   virtual bool converged () override { return true; };
      |                ^~~~~~~~~
make: *** [/home/username/projects/moose//framework/build.mk:151: /home/username/projects/aurora/aurora/openmc/build/unity_src/problem_Unity.x86_64-pc-linux-gnu.opt.lo] Error 1

**Comment by shizhiqijlu** [comment]
probably because moose update it's function, now the function 'converged' need a parameter named "const unsigned int nl_sys_num", thus the old code does not make an override.
 i don't quite understand what this parameter stand for, it's something about nonlinear system equation and it is a wrapped parameter that user don't need to specify. so i ignore the upcoming error about test function implemented for checking function in class 'openmcproblem'

**Comment by shizhiqijlu** [comment]
/projects/aurora/aurora/openmc/unit/src/OpenMCProblemTest.C:39:32: error: no matching function for call to 'FEProblemBase::converged()'
   39 |   EXPECT_TRUE(problem.converged());

/projects/aurora/aurora/openmc/unit/src/OpenMCProblemTest.C:42:32: error: no matching function for call to 'FEProblemBase::solve()'
   42 |   ASSERT_NO_THROW(problem.solve());

/projects/aurora/aurora/openmc/unit/src/OpenMCProblemTest.C:43:32: error: no matching function for call to 'FEProblemBase::converged()'
   43 |   EXPECT_TRUE(problem.converged());
